### PR TITLE
move polyfill to scoped function

### PR DESCRIPTION
**Pull request by paulcpederson**

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Do you want to change the `main` field in the package.json?

**Comment by paulcpederson** [comment]
@thejameskyle to `focusin-polyfill.js`? I don't know, what do you think? My thought was that if people are loading it via npm for the client they are going to `require` it, so it's not much more work to call `polyfill` as well? What do you think?

**Comment by jamiebuilds** [comment]
Well, looking at npm download stats it looks like we're the only two using this. Idk if you need to optimize for people that don't yet exist. I do think this is the preferred api for polyfilling for npm users though

**Comment by paulcpederson** [comment]
@thejameskyle haha. Goood points. I like the explicit nature of `.polyfill` as I think it's less magic. Going to merge this and push 2.0.

**Comment by paulcpederson** [comment]
Leaving the `main` as this fixes your issue and I don't mind typing `polyfill`

**Pull request merged**
